version: '3.8'
services:
  sender:
    container_name: sender
    build:
      context: ./sender
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    working_dir: /app
    ports:
      - "8080:8080"
    # depends_on:
    #   - senrec_mongodb

  reciever:
    container_name: reciever
    build:
      context: ./reciever
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    working_dir: /app
    ports:
      - "8081:8081"
    # depends_on:
    #   - senrec_mongodb


  # senrec_mongodb:
  #   image: mongo:latest
  #   container_name: senrec_mongodb
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db

volumes:
  mongo-data: